import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import Link from 'next/link';
import { SiteNav } from './_components/shared/site-nav';
import { Scrollbar } from './_components/shared/scrollbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'scrollbar',
                'font-sans',
                inter.variable,
            )}>
            <body className='min-h-full flex flex-col'>
                <header className='sticky top-0 z-50 border-b border-white/10 bg-black/35 backdrop-blur-md'>
                    <nav className='mx-auto flex w-full max-w-6xl items-center justify-between gap-4 px-6 py-4 sm:px-10'>
                        <Link
                            href='/'
                            className='text-sm font-semibold uppercase tracking-[0.3em] text-white'>
                            Aeroc
                        </Link>
                        <SiteNav />
                    </nav>
                </header>
                <Scrollbar />
                <div className='flex-1'>{children}</div>
            </body>
        </html>
    );
}
