import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import { SiteHeader } from './_components/shared/site-header';
import { Scrollbar } from './_components/shared/scrollbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'scrollbar',
                'font-sans',
                inter.variable,
            )}>
            <body className='min-h-full flex flex-col'>
                <SiteHeader />
                <Scrollbar />
                <div className='flex-1'>{children}</div>
            </body>
        </html>
    );
}
